server:
  port: 80

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hackathon
    username: hackathon
    password: hackathon
    socketTimeout: 10
